# Generated by Django 5.0.7 on 2024-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_house_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='coffees',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
